[Main]
#log_level =

[Bot]
#token = 
#username = 
#avatar = 
#banner = 
#activity =
#ping_message =
#ping_url = 
#uptime_url =
#uptime_token =
#owner_id = 

[PostgreSQL]
#database = 
#password = 
#host =
#port = 
#user = 
#max_connections = 

[Server]
#translate =
#search =
#llm_host_text =
#llm_host_tts =
#llm_host_stt =
#text_gen_model =
#image_to_text_model =
#text_to_speech_model = 
#speech_to_text_model = 

[API-Info]
#gif_token =
#cloudflare_token =
#cloudflare_token_fallback = 
#cloudflare_image_gen = 
#cloudflare_image_gen_fallback = 

[HTTP-Agent]
#title = ""
#repo = ""
#email = ""
